version: '3.8'

services:

  react-app:
    container_name: rk-test2
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      # - /app
      - react-app-data:/app/node_modules
    depends_on:
      - keycloack

  

  keycloack:
    image: jboss/keycloak
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/temp/realm-import.json
      - DB_VENDOR=H2
    volumes:
      - ./data/keycloak:/temp

volumes:
  react-app-data:
